## CSS Project Part 2
Arathy Pillai, Alexander Guth, Hammad Akthar, Hiba Saleel and Julian Jetz

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from string import punctuation

In [2]:
plot_size = plt.rcParams["figure.figsize"]  
plot_size[0] = 15  
plot_size[1] = 8  
plt.rcParams["figure.figsize"] = plot_size  

### Load data and determine na values
repost and Text are determined as na values, because they ... **[TODO]**

In [3]:
na_values = ['nan', 'N/A', 'NaN', 'NaT', '0', '', 'Text', 'repost', 'r e p o s t -', 'Repost']
ira_data = pd.read_csv('../Data/data_IRA_Ads.csv', sep=";", parse_dates=['AD_CREATION_DATE', 'AD_END_DATE'], 
                       dayfirst=False, index_col='AD_ID', na_values=na_values)

### Click per View Ratio
#Clicks / #Impressions

In [4]:
ira_data.insert(5, 'AD_CLICKS_PER_VIEW', ira_data['AD_CLICKS']/ira_data['AD_IMPRESSIONS'])

### Convert ruble
Removes "RUB" from the cell AD_SPEND

In [5]:
ira_data['AD_SPEND']=ira_data['AD_SPEND'].str.replace(' RUB','')

### Cleaning up targeting data

In [6]:
def remove_punctuation_at_the_end(x):
    #remove "," and "." and ":" from the end of x
    x = x.rstrip(',')
    x = x.rstrip('.')
    x = x.rstrip(':')
    #replace ";" and ",." with "," in x
    x = x.replace(';', ',')
    x = x.replace(',.', ',')
    return x

In [7]:
#replace abbreviations with their long form in AD_TARGETING_EXCLUDED_CONNECTIONS
ira_data['AD_TARGETING_EXCLUDED_CONNECTIONS']=ira_data['AD_TARGETING_EXCLUDED_CONNECTIONS'].str.replace('Exclude people who like BM','Exclude people who like Black Matters')

#replace ")or" (missing space) with ") or" and ");" with ")," in AD_TARGETING_LANGUAGE due to having a different formats used
ira_data['AD_TARGETING_LANGUAGE'] = ira_data['AD_TARGETING_LANGUAGE'].str.replace('\)or', ') or')
ira_data['AD_TARGETING_LANGUAGE'] = ira_data['AD_TARGETING_LANGUAGE'].str.replace('\);', '),')

#??Remove lines without AD_TARGETING_INTERESTS and execute remove_punctuation_at_the_end on each string in AD_TARGETING_INTERESTS
ira_data['AD_TARGETING_INTERESTS'] = ira_data['AD_TARGETING_INTERESTS'].dropna().apply(lambda x: remove_punctuation_at_the_end(str(x)))
ira_data['AD_TARGETING_PEOPLE_WHO_MATCH'] = ira_data['AD_TARGETING_PEOPLE_WHO_MATCH'].dropna().apply(lambda x: remove_punctuation_at_the_end(str(x)))
ira_data['AD_TARGETING_EXCLUDE'] = ira_data['AD_TARGETING_EXCLUDE'].dropna().apply(lambda x: remove_punctuation_at_the_end(str(x)))

### Add column for amount of different targeted interests
**TODO** Control result of count function, include Behavior: (browser): 

In [8]:
def replace_target_seperator(x):
    x = x.replace(' or ', ',')
    x = x.replace(',,', ',')
    x = x.replace('AND MUST ALSO MATCH:', ',')
    x = x.replace(', Jr.', ' Jr.')
    x = x.replace('. ', ', ')
    return x

In [9]:
ira_data.insert(12, 'AD_TARGETING_EXCLUDE_COUNT', np.NaN)
ira_data.insert(17, 'AD_TARGETING_INTEREST_COUNT', np.NaN)
ira_data.insert(23, 'AD_TARGETING_PEOPLE_WHO_MATCH_COUNT', np.NaN)

In [10]:
ira_data['AD_TARGETING_EXCLUDE_COUNT'] = ira_data['AD_TARGETING_EXCLUDE'].dropna().apply(lambda x: len(replace_target_seperator(str(x)).split(',')))

In [11]:
ira_data['AD_TARGETING_INTEREST_COUNT'] = ira_data['AD_TARGETING_INTERESTS'].dropna().apply(lambda x: len(replace_target_seperator(str(x)).split(',')))

In [12]:
ira_data['AD_TARGETING_PEOPLE_WHO_MATCH_COUNT'] = ira_data['AD_TARGETING_PEOPLE_WHO_MATCH'].dropna().apply(lambda x: len(replace_target_seperator(str(x)).split(',')))

In [13]:
pd.set_option('display.max_colwidth', -1)
ira_data[['AD_TARGETING_EXCLUDE', 'AD_TARGETING_EXCLUDE_COUNT', 'AD_TARGETING_INTERESTS', 'AD_TARGETING_INTEREST_COUNT', 'AD_TARGETING_PEOPLE_WHO_MATCH', 'AD_TARGETING_PEOPLE_WHO_MATCH_COUNT']].sample(20)

AD_TARGETING_EXCLUDE  AD_TARGETING_EXCLUDE_COUNT  \
AD_ID                                                    
2517   NaN                 NaN                           
963    NaN                 NaN                           
1722   NaN                 NaN                           
1423   NaN                 NaN                           
3328   NaN                 NaN                           
1311   NaN                 NaN                           
1707   NaN                 NaN                           
272    NaN                 NaN                           
3110   NaN                 NaN                           
429    NaN                 NaN                           
514    NaN                 NaN                           
1744   NaN                 NaN                           
2701   NaN                 NaN                           
336    NaN                 NaN                           
1669   NaN                 NaN                           
2965   NaN                 NaN                           
2348   NaN                 NaN                           
1435   NaN                 NaN                           
1963   NaN                 NaN                           
1858   NaN                 NaN                           

                                                                                                                                                                                                                                                                                       AD_TARGETING_INTERESTS  \
AD_ID                                                                                                                                                                                                                                                                                                           
2517   Martin Luther King, Jr., Police Brutality is a Crime, Police misconduct, African-American culture, African-American Civil Rights Movement ( 1954-68), African-American history, Black Consciousness Movement, Police brutality in the United States, Stop Police Brutality, Malcolm X or Black (Color)   
963    Black nationalism, Pan-Africanism, Police misconduct, African-American culture, African-American Civil Rights Movement ( 1954-68), African-American history, Black Consciousness Movement, Martin Luther King Ill, Stop Police Brutality or Black (Color)                                                
1722   Imgur or iFunny                                                                                                                                                                                                                                                                                          
1423   NaN                                                                                                                                                                                                                                                                                                      
3328   Mixed martial arts, Martial arts, The Women's Self Defense Institute, PERSONAL & HOME DEFENSE, Self-defense, Self- defense (United States), Personal Defense, Right of self-defense, Self Defense Family or Active Self Protection                                                                       
1311   NaN                                                                                                                                                                                                                                                                                                      
1707   NaN                                                                                                                                                                                                                                                                                       

### Drop all subsets, where AD_TEXT is na

In [14]:
ira_data=ira_data.dropna(subset=['AD_TEXT']);
ira_data['AD_TEXT'].count()

3436

### Remove hyperlinks

In [15]:
ira_data['AD_TEXT']=ira_data['AD_TEXT'].str.replace(r'https?:\/\/.*[\r\n]*', '')
ira_data['AD_TEXT']=ira_data['AD_TEXT'].str.replace(r'http?:\/\/.*[\r\n]*', '')

### Select all duplicate ad texts

In [16]:
duplicateDF = pd.concat(g for _, g in ira_data.groupby("AD_TEXT") if len(g) > 1).copy()
duplicateDF.sort_values(by=['AD_TEXT'], inplace=True)

### Total Duplicates

In [17]:
duplicateDF['AD_TEXT'].count()

1438

### Unique Duplicate Pairs

In [18]:
duplicateDF['AD_TEXT'].nunique()

361

### Occurence of Duplicate Pairs

In [19]:
duplicateDF['AD_TEXT'].value_counts().values

array([53, 23, 18, 16, 14, 14, 12, 12, 12, 12, 10, 10, 10, 10, 10, 10, 10,
       10, 10,  9,  9,  9,  9,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2

In [20]:
duplicateDF[duplicateDF['AD_IMPRESSIONS']>0]['AD_TEXT'].value_counts().values

array([13, 12,  9,  8,  7,  7,  6,  6,  6,  6,  6,  6,  6,  6,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

In [21]:
duplicateDF[(duplicateDF['AD_IMPRESSIONS']>0) & duplicateDF['AD_TEXT'].str.match('We speak for all fellow members of LGBT community across the nation.')][['AD_CLICKS', 'AD_IMPRESSIONS', 'AD_CREATION_DATE','AD_TEXT', 'AD_TARGETING_AGE', 'AD_SPEND', 'AD_TARGETING_CUSTOM_AUDIENCE', 'AD_TARGETING_EXCLUDE', 'AD_TARGETING_EXCLUDED_CONNECTIONS', 'AD_TARGETING_INTERESTS', 'AD_TARGETING_LOCATION', 'AD_TARGETING_LOCATION_LIVING_IN', 'AD_TARGETING_FRIENDS_OF_CONNECTIONS', 'AD_TARGETING_PLACEMENTS', 'AD_TARGETING_LANGUAGE', 'AD_TARGETING_PEOPLE_WHO_MATCH', 'AD_POTENTIAL_TARGET']].head(20)

AD_CLICKS  AD_IMPRESSIONS    AD_CREATION_DATE  \
AD_ID                                                  
591    5441.0     93925.0        2016-03-23 05:36:11   
592    7289.0     190076.0       2016-08-04 04:20:05   
590    6566.0     67221.0        2015-11-05 23:11:58   
669    91.0       1997.0         2015-06-17 03:15:18   
588    21449.0    175460.0       2015-07-14 00:01:38   
586    59.0       1811.0         2015-07-07 01:51:07   
585    1252.0     11857.0        2015-07-01 02:55:07   
584    3206.0     31618.0        2015-06-23 05:06:57   
583    186.0      4265.0         2015-06-22 08:19:07   
582    1724.0     18891.0        2015-06-18 00:58:48   
581    36.0       1438.0         2015-06-17 03:15:18   
580    103.0      122.0          2015-06-16 03:36:10   
587    542.0      15175.0        2015-07-09 01:50:28   

                                                                    AD_TEXT  \
AD_ID                                                                         
591    We speak for all fellow members of LGBT community across the nation.   
592    We speak for all fellow members of LGBT community across the nation.   
590    We speak for all fellow members of LGBT community across the nation.   
669    We speak for all fellow members of LGBT community across the nation.   
588    We speak for all fellow members of LGBT community across the nation.   
586    We speak for all fellow members of LGBT community across the nation.   
585    We speak for all fellow members of LGBT community across the nation.   
584    We speak for all fellow members of LGBT community across the nation.   
583    We speak for all fellow members of LGBT community across the nation.   
582    We speak for all fellow members of LGBT community across the nation.   
581    We speak for all fellow members of LGBT community across the nation.   
580    We speak for all fellow members of LGBT community across the nation.   
587    We speak for all fellow members of LGBT community across the nation.   

      AD_TARGETING_AGE  AD_SPEND AD_TARGETING_CUSTOM_AUDIENCE  \
AD_ID                                                           
591    18 - 54          31713.12  NaN                           
592    18 - 54          36000.00  NaN                           
590    18 - 54          46994.76  NaN                           
669    18 - 65+         2673.94   NaN                           
588    18 - 65+         93754.38  NaN                           
586    18 - 65+         757.65    NaN                           
585    18 - 65+         5538.24   NaN                           
584    18 - 65+         16630.20  NaN                           
583    18 - 65+         1393.55   NaN                           
582    18 - 65+         10085.77  NaN                           
581    18 - 65+         1362.57   NaN                           
580    18 - 65+         129.66    NaN                           
587    18 - 65+         6201.70   NaN                           

      AD_TARGETING_EXCLUDE    AD_TARGETING_EXCLUDED_CONNECTIONS  \
AD_ID                                                             
591    NaN                  NaN                                   
592    NaN                  NaN                                   
590    NaN                  Exclude people who like LGBT United   
669    NaN                  Exclude people who like LGBT United   
588    NaN                  Exclude people who like LGBT United   
586    NaN                  Exclude people who like LGBT United   
585    NaN                  Exclude people who like LGBT United   
584    NaN                  Exclude people who like LGBT United   
583    NaN                  Exclude people who like LGBT United   
582    NaN                  Exclude people who like LGBT United   
581    NaN                  Exclude people who like LGBT United   
580    NaN                  Exclude people who like LGBT United   
587    NaN                  Exclude people who like LGBT United   

In [22]:
#fig1, ax1 = plt.subplots()
#ind = np.arange(duplicateDF[(duplicateDF['AD_IMPRESSIONS']>0) & duplicateDF['AD_TEXT'].str.match('We speak for all fellow members of LGBT community across the nation.')]['AD_TARGETING_INTEREST_COUNT'].count)    # the x locations for the groups
#width = 0.35 
#ax1.bar(duplicateDF[(duplicateDF['AD_IMPRESSIONS']>0) & duplicateDF['AD_TEXT'].str.match('We speak for all fellow members of LGBT community across the nation.')]['AD_TARGETING_INTEREST_COUNT'], width)
#plt.show()

In [23]:
duplicateDF['AD_TARGETING_AGE'].unique()

array(['18 - 65+', '16 - 65+', '15 - 54', '15 - 25', '14 - 17', '15 - 30',
       '18 - 51', '18 - 54', '18 65+', '17 - 65+', '40 - 65+', '30 - 65+',
       '20 - 65+', '45 - 64', '24 - 45', '18 - 50', '25 - 65+',
       '13 - 65+', '35 - 65+', '21 - 65+', '18 - 45', '13 - 44',
       '14 - 40', '15 - 65+', '19 - 30', '20 - 45', '13 - 30', '13 - 45',
       '18 - 59', '18 - 48', '16 - 55', '14 - 54', '16 - 54', '16 - 45',
       '14 - 65+', '13 - 40', '45 - 65+', '18 - 53', '18 - 39', '18 - 61',
       '16 - 53', '13 - 60', '24 - 65+', '18 - 60', '15 - 26'],
      dtype=object)

In [24]:
duplicateDF['AD_TARGETING_CUSTOM_AUDIENCE'].value_counts()

Lookalike(US, 1%)- People who like Defend the 2nd               6
Lookalike(US, 1%)- newtestaudit                                 3
tesy                                                            2
Lookalike(US, 1%)- People who like United Muslims of America    2
Lookalike(US, 10%)- tesy                                        2
Lookalike(US, 1%)- tr                                           1
Lookalike(US, 10%)- newtestaudit                                1
Name: AD_TARGETING_CUSTOM_AUDIENCE, dtype: int64

In [25]:
duplicateDF['AD_TARGETING_EXCLUDE'].value_counts()

Behaviors: Hispanic(US - All), Hispanic(US - Spanish dominant), Hispanic(US - English dominant), Hispanic(US - Bilingual: English and Spanish) or Asian American (US)    36
Multicultural Affinity: Hispanic(US - All), Hispanic(US - Spanish dominant), Hispanic(US - English dominant), Hispanic(US - Bilingual) or Asian American (US)            8 
Multicultural Affinity: Hispanic (US - All), Hispanic (US - Spanish dominant), Hispanic (US - English dominant), Hispanic (US - Bilingual) or Asian American (US)        2 
Multicultural Affinity: Hispanic(US -All), Hispanic(US - Spanish dominant), Hispanic(US - English dominant), Hispanic(US - Bilingual) or Asian American (US)             2 
Behaviors Hispanic(US - All), Hispanic(US - Spanish dominant), Hispanic(US - English dominant), Hispanic(US - Bilingual: English and Spanish) or Asian American (US)     1 
Name: AD_TARGETING_EXCLUDE, dtype: int64

In [26]:
duplicateDF['AD_TARGETING_EXCLUDED_CONNECTIONS'].value_counts()

Exclude people who like Black Matters                                    92
Exclude people who like Stop A.1.                                        77
Exclude people who like Williams&Kalvin                                  71
Exclude people who like Defend the 2nd                                   65
Exclude people who like Stop Refugees                                    50
Exclude people who like Blacktivist                                      46
Exclude people who like Don't Shoot                                      40
Exclude people who like United Muslims of America                        36
Exclude people who like Heart of Texas                                   35
Exclude people who like Black4Black                                      23
Exclude people who like LGBT United                                      21
Exclude people who like Secured Borders                                  16
Exclude people who like Veterans Come First                              15
Exclude peop

In [27]:
duplicateDF['AD_TARGETING_INTERESTS'].nunique()

336

In [28]:
duplicateDF['AD_TARGETING_LOCATION'].nunique()

55

In [29]:
duplicateDF['AD_TARGETING_LOCATION_LIVING_IN'].value_counts().values

array([335,  43,  19,  18,  11,   6,   6,   5,   5,   4,   4,   3,   3,
         3,   3,   3,   3,   3,   3,   2,   2,   2,   2,   2,   2,   2,
         2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1])

In [30]:
duplicateDF['AD_TARGETING_FRIENDS_OF_CONNECTIONS'].value_counts()

Friends of people who are connected to Black Matters      17
Friends of people who are connected to Don't Shoot        9 
Friends of people who are connected to LGBT United        5 
Friends of people who are connected to Williams&Kalvin    1 
Name: AD_TARGETING_FRIENDS_OF_CONNECTIONS, dtype: int64

In [31]:
duplicateDF['AD_TARGETING_PLACEMENTS'].value_counts().values

array([920, 254,  99,  66,  27,  12,  10,   9,   8,   7,   4,   4,   4,
         3,   2,   2,   1,   1,   1,   1,   1,   1,   1])

In [32]:
duplicateDF['AD_TARGETING_LANGUAGE'].value_counts()

English (UK) or English (US)                              868
English (US)                                              70 
English (UK), Arabic or English (US)                      33 
Spanish, English (UK), English (US) or Spanish (Spain)    4  
Name: AD_TARGETING_LANGUAGE, dtype: int64

In [33]:
duplicateDF['AD_TARGETING_PEOPLE_WHO_MATCH'].value_counts().values

array([61, 14, 13, 13,  9,  8,  6,  6,  6,  5,  5,  4,  3,  3,  3,  2,  2,
        2,  2,  2,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [35]:
duplicateDF.sample(25)

AD_CLICKS    AD_CREATION_DATE         AD_END_DATE  AD_IMPRESSIONS  \
AD_ID                                                                      
2403   1112.0    2016-10-06 06:20:34 2016-10-22 04:18:29  24857.0          
402   NaN        2015-07-02 03:10:36 NaT                 NaN               
1502  NaN        2016-07-06 07:06:04 2016-05-14 07:16:12 NaN               
1216  NaN        2016-10-05 06:07:30 NaT                 NaN               
1381  NaN        2016-03-10 06:10:18 NaT                 NaN               
3014   29.0      2016-10-14 06:01:41 NaT                  1339.0           
3347   74.0      2017-03-31 06:57:14 2017-04-01 06:57:14  1974.0           
2375  NaN        2016-10-26 06:12:51 2016-10-03 04:47:13 NaN               
1494   2052.0    2016-05-13 07:17:06 2016-05-16 07:17:05  10986.0          
2778  NaN        2017-02-20 06:37:54 NaT                 NaN               
3373   3.0       2017-02-06 07:15:59 2017-02-11 15:29:15  67.0             
2976   12.0      2016-10-18 07:54:56 NaT                  199.0            
3479  NaN        2016-05-11 00:17:48 NaT                 NaN               
737    689.0     2015-09-22 07:43:19 NaT                  6687.0           
2978   17.0      2016-10-19 07:44:01 NaT                  283.0            
1697  NaN        2016-03-23 07:43:04 2016-03-26 16:39:00  12518.0          
590    6566.0    2015-11-05 23:11:58 NaT                  67221.0          
1352  NaN        2016-05-05 03:27:06 NaT                 NaN               
2204  NaN        2016-10-26 06:13:56 2016-09-29 05:33:44 NaN               
2335   294.0     2016-09-30 04:38:37 2016-10-01 04:38:36  2329.0           
2952  NaN        2017-04-19 07:47:54 NaT                 NaN               
1614   361.0     2015-12-18 03:59:48 NaT                  7217.0           
2235   42.0      2016-09-27 08:23:07 2016-09-29 08:23:06  324.0            
462    1.0       2016-04-13 03:24:25 NaT                  60.0             
1331  NaN        2016-05-05 03:30:30 2016-05-07 03:30:29 NaN               

                                                                                 AD_LANDING_PAGE  \
AD_ID                                                                                              
2403   https://www.facebook.com/blackmattersus/.mvmnt/                                             
402    https://www.facebook.com/black-matters-1579673598947501/                                    
1502   https://www.facebook.com/dont-shoot-1157233400960126/                                       
1216   https://www.facebook.com/blacktivists/                                                      
1381   https://www.facebook.com/stop-al-896610653786585/                                           
3014   https://www.facebook.com/black—liberation—church-1160193507389202/                          
3347   https://www.meetup.com/black-fist-self-defense-project/                                     
2375   https://www.facebook.com/blackmattersus/.mvmnt/                                             
1494   https://www.facebook.com/dont-shoot-1157233400960126/                                       
2778   https://www.facebook.com/south-united-1777037362551238/                                     
3373   https://www.facebook.com/events/694209204073106/                                            
2976   https://www.facebook.com/liberty-rising-692068924291672/                                    
3479   https://musicfb.info/                                                                       
737    https://www.facebook.com/timetosecede/                                                      
2978   https://www.facebook.com/liberty-rising-692068924291672/                                    
1697   https://www.facebook.com/blackiuive-1725227467722991/                                       
590    https://www.facebook.com/igbtun/                                                            
1352   https://www.facebook.com/stop-al-89661065378658